### ISSUE TITLE
Optional frontend, backend, mobile

### ISSUE THREAD

**Issue by Chralu** [thetribeio/generator-project#763]
Hi,

at the moment, there is no way to generate only a [back | front].
It could be useful to generate only one of those parts.

What about adding a `None` value to `What Backend do you use` and `What Frontend do you use` ?

**Comment by jvasseur** [comment]
It's already possible by running only the sub-generators, for example for just an express backend:
```
yo @thetribe/project:root
yo @thetribe/express backend --http-path=/
```

But adding a None option to the main generator wouldn't cost us a lot and could make this use case easier so why not.
