### ISSUE TITLE
yarn test:generators => attempt to override $UID readonly variable

### ISSUE THREAD

**Issue by Chralu** [thetribeio/generator-project#770]
When running `$ yarn test:generators` I get the following error : `script/lib/docker: line 2: UID: readonly variable`.

Indeed, script `generators/root/templates/base/script/lib/docker` attempts to set `$UID` global var, which is reserved by some shells.

Running environment : 
  - Shell : zsh 5.8
  - OS : MacOS 12.0.1

**Comment by jvasseur** [comment]
That's strange, this script is only called by the scripts in the `script` directory that use a shebang of `#!/bin/sh` that doesn't have this special variable. Maybe MacOS implementation of `sh` doesn't work the same way.

Anyway we can easily rename this variable to fix this problem.

**Comment by Chralu** [comment]
Apple ways 😅 : 

```sh
$ which sh
/bin/sh

$ sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```
